spring:
  application:
    name: lxp

  h2:
    console:
      enabled: false

  jpa:
    hibernate:
      ddl-auto: none
    show-sql: false
    properties:
      hibernate:
        format_sql: false

server:
  port: 8080

lxp:
  auth:
    jwt:
      secret: ${JWT_SECRET:}
      access-token-expiration-minutes: 30
      refresh-token-expiration-days: 14
