spring:
  application:
    name: lxp

  datasource:
    url: jdbc:h2:mem:lxpdb;MODE=MySQL;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    driver-class-name: org.h2.Driver
    username: sa
    password:

  h2:
    console:
      enabled: false

  jpa:
    hibernate:
      ddl-auto: create
    show-sql: false
    properties:
      hibernate:
        format_sql: false

server:
  port: 8080

lxp:
  auth:
    jwt:
      secret: ${JWT_SECRET:asdfasdfasdfasdfasdfasdfasdfasdfasdfasdfasdfasdfasdfasdfasdfasdfasdf}
      access-token-expiration-minutes: 30
      refresh-token-expiration-days: 14
