import type { Question } from './types';

export const MOCK_QUESTIONS: Question[] = [
  {
    id: 'q1',
    courseId: '3',
    courseTitle: '프론트엔드 마스터: React & TypeScript',
    memberId: 'u1',
    authorName: '박민준',
    title: 'React Server Components의 동작 원리가 궁금합니다.',
    content:
      '안녕하세요, 강의 잘 듣고 있습니다 :)\n\nReact 18에서 도입된 Server Components의 동작 원리를 좀 더 깊게 이해하고 싶습니다. 기존의 SSR(Server Side Rendering)과 Server Components가 구체적으로 어떤 점이 다른가요? 특히 번들 크기와 Server Components가 완전히 다른 패러다임인지 궁금합니다.',
    isAnswered: true,
    tags: ['Next.js', 'React'],
    createdAt: '2일 전',
    updatedAt: '1일 전',
    answer: {
      id: 'a1',
      questionId: 'q1',
      authorId: 'u2',
      authorName: '이서연',
      createdAt: '1일 전',
      updatedAt: '1일 전',
      avatarSrc: 'https://lh3.googleusercontent.com/aida-public/AB6AXuB5ZHz0kUwUvNwbInMtKkHfVWB6Ig_-YH-3TqJV4uGMMrCftPFfiD2afbP4cr8B3dPILzpBKUu0hmDHodLaoDQoVB7TfOPgavXxGew1YtC4jXcMzk9TShaDvbm-halqDurHe2PIPSWQ8_LtqVORIYHw-j0YJdtMOJcZBI_t4t7kqtJ4RuRRe9AX5Y98sYgNIU5qB_GTcwnmceFWXpXjU11eYka9_blVhHlK4GVqEqY_ZknID2hNEqbZEf4vm71JEJu0G6Roj5jJv_7N',
      content:
        '좋은 질문입니다! "서버에서 렌더링한다"는 공통점이 있지만 핵심 차이가 있습니다.\n\n• SSR은 매 요청마다 전체 컴포넌트 트리를 서버에서 HTML로 렌더링한 뒤 클라이언트로 전송하고, 이후 JS 번들로 하이드레이션(hydration)이 일어납니다.\n• RSC(React Server Components)는 특정 컴포넌트를 아예 클라이언트 번들에서 제외합니다. 서버에서만 실행되며 직렬화된 React 트리로 전달되기 때문에 해당 컴포넌트의 JS가 브라우저로 내려가지 않습니다.\n\n쉽게 말해, SSR은 "서버에서 HTML을 만들어 보내지만 JS는 여전히 클라이언트로 가는" 방식이고, RSC는 "특정 컴포넌트의 JS 자체를 클라이언트에 보내지 않는" 방식입니다.',
    },
  },
  {
    id: 'q2',
    courseId: '3',
    courseTitle: '프론트엔드 마스터: React & TypeScript',
    memberId: 'u7',
    authorName: '이준호',
    title: 'Tailwind CSS v4 마이그레이션 방법이 궁금합니다.',
    content: 'v3에서 v4로 마이그레이션할 때 주의해야 할 breaking change가 무엇인지 알고 싶습니다.',
    isAnswered: false,
    tags: ['Tailwind', 'CSS'],
    createdAt: '3일 전',
    updatedAt: '3일 전',
    answer: null,
  },
  {
    id: 'q3',
    courseId: '2',
    courseTitle: 'AI 프로그래밍 기초',
    memberId: 'u8',
    authorName: '박지민',
    title: 'Figma 디자인토큰을 코드와 동기화하는 방법 질문이 있습니다.',
    content: 'Figma Variables와 CSS 커스텀 프로퍼티를 자동으로 동기화하는 방법을 찾고 있습니다.',
    isAnswered: false,
    tags: ['Figma', '디자인시스템'],
    createdAt: '5일 전',
    updatedAt: '5일 전',
    answer: null,
  },
  {
    id: 'q4',
    courseId: '1',
    courseTitle: 'Python으로 시작하는 데이터 분석',
    memberId: 'u2',
    authorName: '김수현',
    title: 'pandas DataFrame에서 NaN 처리할 때 fillna vs dropna 어떤 걸 써야 하나요?',
    content:
      '안녕하세요! 데이터 전처리 강의에서 결측값 처리를 배우고 있는데요.\n\n실습 데이터에서 NaN이 꽤 많이 나오는데, fillna()로 특정 값을 채우는 게 나은지 아니면 dropna()로 행 자체를 제거하는 게 나은지 판단 기준이 헷갈립니다.',
    isAnswered: true,
    tags: ['pandas', 'Python'],
    createdAt: '1일 전',
    updatedAt: '1일 전',
    answer: {
      id: 'a4',
      questionId: 'q4',
      authorId: 'u4',
      authorName: '최재원',
      createdAt: '1일 전',
      updatedAt: '1일 전',
      avatarSrc: 'https://lh3.googleusercontent.com/aida-public/AB6AXuCpW1lxL5W-xjUFr-8xb4JsEhZGEOr0SX8aVfbR6tUknVYdPQmBqkdmSbYjCJPy4sj3HYSwf3ILqHXBujr8tO4B7CGb5L0kgAp9YOAQ2M5-hhDxAtQ9UD0BfqmhZEaAQWpqGBx1E7V-b-y-JwNjMRMpLj8Vqnz7Ss7qNbHB4g5H48LqW9r_bBQFQpkCKMvPi6D1bRr5lGBYcZWP2Wt3nEj8YjsLbJe4GGqHE5OXqmz0fJL9-HJkVY04cH0LoFkr8SiPMthPkGRD',
      content:
        '아주 좋은 질문입니다! 실무 기준으로 설명해 드릴게요.\n\n• dropna() 권장: 결측값이 5% 미만이고 해당 행이 분석에 필수가 아닐 때.\n• fillna() 권장: 결측값이 많아 dropna() 시 데이터가 너무 줄어들 때. 수치형은 중앙값(median), 범주형은 최빈값(mode)으로 채웁니다.',
    },
  },
  {
    id: 'q5',
    courseId: '1',
    courseTitle: 'Python으로 시작하는 데이터 분석',
    memberId: 'u3',
    authorName: '오태양',
    title: 'matplotlib 그래프가 Jupyter에서 출력이 안 됩니다.',
    content:
      'plt.show()를 호출해도 그래프가 나타나지 않고 아무 출력도 없습니다. %matplotlib inline 설정을 했는데도 동일합니다.',
    isAnswered: true,
    tags: ['matplotlib', 'Jupyter'],
    createdAt: '4일 전',
    updatedAt: '3일 전',
    answer: {
      id: 'a5',
      questionId: 'q5',
      authorId: 'u4',
      authorName: '최재원',
      createdAt: '3일 전',
      updatedAt: '3일 전',
      avatarSrc: 'https://lh3.googleusercontent.com/aida-public/AB6AXuCpW1lxL5W-xjUFr-8xb4JsEhZGEOr0SX8aVfbR6tUknVYdPQmBqkdmSbYjCJPy4sj3HYSwf3ILqHXBujr8tO4B7CGb5L0kgAp9YOAQ2M5-hhDxAtQ9UD0BfqmhZEaAQWpqGBx1E7V-b-y-JwNjMRMpLj8Vqnz7Ss7qNbHB4g5H48LqW9r_bBQFQpkCKMvPi6D1bRr5lGBYcZWP2Wt3nEj8YjsLbJe4GGqHE5OXqmz0fJL9-HJkVY04cH0LoFkr8SiPMthPkGRD',
      content:
        '체크리스트를 드릴게요.\n\n1. %matplotlib inline 은 import matplotlib.pyplot 보다 앞 셀에서 실행해야 합니다.\n2. VS Code Jupyter라면 %matplotlib widget 을 사용해 보세요.\n3. pip install ipykernel 후 커널을 다시 선택해 보세요.',
    },
  },
  {
    id: 'q6',
    courseId: '3',
    courseTitle: '프론트엔드 마스터: React & TypeScript',
    memberId: 'u4',
    authorName: '윤지아',
    title: 'TypeScript에서 unknown vs any 차이가 헷갈립니다.',
    content:
      'any를 쓰면 타입 체크를 전혀 안 하는 건 알겠는데, unknown은 언제 쓰는 건지 명확하게 이해가 안 됩니다.',
    isAnswered: false,
    tags: ['TypeScript'],
    createdAt: '6일 전',
    updatedAt: '6일 전',
    answer: null,
  },
  {
    id: 'q7',
    courseId: '2',
    courseTitle: 'AI 프로그래밍 기초',
    memberId: 'u5',
    authorName: '임도현',
    title: 'LLM API 호출 시 토큰 비용 최소화하는 방법이 있을까요?',
    content:
      '프로젝트에서 OpenAI API를 연동했는데 테스트만 했는데도 비용이 생각보다 많이 나왔습니다.',
    isAnswered: true,
    tags: ['LLM', 'OpenAI', '비용최적화'],
    createdAt: '1주 전',
    updatedAt: '6일 전',
    answer: {
      id: 'a7',
      questionId: 'q7',
      authorId: 'u4',
      authorName: '김나영',
      createdAt: '6일 전',
      updatedAt: '6일 전',
      avatarSrc: 'https://lh3.googleusercontent.com/aida-public/AB6AXuB5ZHz0kUwUvNwbInMtKkHfVWB6Ig_-YH-3TqJV4uGMMrCftPFfiD2afbP4cr8B3dPILzpBKUu0hmDHodLaoDQoVB7TfOPgavXxGew1YtC4jXcMzk9TShaDvbm-halqDurHe2PIPSWQ8_LtqVORIYHw-j0YJdtMOJcZBI_t4t7kqtJ4RuRRe9AX5Y98sYgNIU5qB_GTcwnmceFWXpXjU11eYka9_blVhHlK4GVqEqY_ZknID2hNEqbZEf4vm71JEJu0G6Roj5jJv_7N',
      content:
        '비용 최적화 방법을 정리해 드릴게요.\n\n• 모델 선택: 간단한 작업은 gpt-4o-mini로도 충분합니다.\n• 캐싱: 동일한 프롬프트 응답을 Redis에 캐시하면 중복 호출을 줄입니다.\n• 시스템 프롬프트 최적화: 명확하고 짧은 지시문을 사용하세요.\n• max_tokens 설정: 응답 최대 길이를 명시적으로 제한하세요.',
    },
  },
  {
    id: 'q8',
    courseId: '1',
    courseTitle: 'Python으로 시작하는 데이터 분석',
    memberId: 'u9',
    authorName: '한소희',
    title: 'scikit-learn에서 train_test_split 비율을 어떻게 정해야 하나요?',
    content:
      '강의에서는 80:20을 사용했는데, 데이터가 적을 때도 같은 비율을 써야 하나요?',
    isAnswered: false,
    tags: ['scikit-learn', 'Python'],
    createdAt: '2일 전',
    updatedAt: '2일 전',
    answer: null,
  },
  {
    id: 'q9',
    courseId: '1',
    courseTitle: 'Python으로 시작하는 데이터 분석',
    memberId: 'u10',
    authorName: '정재현',
    title: 'groupby 후 여러 집계 함수를 동시에 적용하는 방법이 있나요?',
    content:
      'groupby를 사용할 때 mean()만 쓰면 되는데, 동시에 sum()이나 count()도 같이 보고 싶습니다.',
    isAnswered: false,
    tags: ['pandas', 'Python'],
    createdAt: '3일 전',
    updatedAt: '3일 전',
    answer: null,
  },
  {
    id: 'q10',
    courseId: '3',
    courseTitle: '프론트엔드 마스터: React & TypeScript',
    memberId: 'u11',
    authorName: '이하은',
    title: 'useEffect 의존성 배열에 함수를 넣으면 무한 루프가 되는 이유가 궁금합니다.',
    content:
      'useEffect 안에서 props로 받은 콜백 함수를 호출하고, 그 함수를 의존성 배열에 넣었더니 무한 렌더링이 발생했습니다.',
    isAnswered: false,
    tags: ['React', 'Hooks'],
    createdAt: '1일 전',
    updatedAt: '1일 전',
    answer: null,
  },
  {
    id: 'q11',
    courseId: '3',
    courseTitle: '프론트엔드 마스터: React & TypeScript',
    memberId: 'u12',
    authorName: '박준서',
    title: 'Next.js에서 환경변수를 클라이언트에서 사용하려면 어떻게 해야 하나요?',
    content:
      '.env.local에 API 키를 넣었는데 클라이언트 컴포넌트에서 undefined가 뜹니다.',
    isAnswered: false,
    tags: ['Next.js', '환경변수'],
    createdAt: '5일 전',
    updatedAt: '5일 전',
    answer: null,
  },
  {
    id: 'q12',
    courseId: '2',
    courseTitle: 'AI 프로그래밍 기초',
    memberId: 'u13',
    authorName: '최유진',
    title: 'RAG 구현 시 청크 크기를 어떻게 설정해야 할까요?',
    content:
      'PDF 문서를 벡터 DB에 임베딩하는 실습을 하고 있습니다. 청크 크기와 오버랩을 어떤 기준으로 설정해야 하나요?',
    isAnswered: false,
    tags: ['RAG', 'LLM', '벡터DB'],
    createdAt: '2일 전',
    updatedAt: '2일 전',
    answer: null,
  },
];

export const getQuestionById = (id: string) =>
  MOCK_QUESTIONS.find((q) => q.id === id) ?? null;
