export const MOCK_COURSES = [
  {
    id: '1',
    title: '데이터 중심의 UI/UX 디자인 실무 입문',
    instructor: '이하연',
    instructorId: 'u2',
    category: 'UI/UX',
    level: '입문',
    thumbnail: 'https://lh3.googleusercontent.com/aida-public/AB6AXuBQT1hP1m52OoE9ZoWN_OQfBhbL6etO0LlpXHRDV2AijJPUmVZ4AznNiZXMLCDkUYETJAlMMFT8dYLJsZ_SgdFcX_bY_iN7DW6nGhqIDREiTjmBHFVgd8RkDMnllbZfVi88xCFGmkDPEE3gkqJPzLvIEHsxwKmxvJvKJGjuqluCe5IQbZkOl9x7qEeAmORxkMlYp3MXZIfpDGovbU6Mm-c4mGe_7yFuB-7d7UKjfZxrQVnERj4e26fBHwLQ4cGvZ02UcKHtNzqFCMQ',
    enrollmentCount: 1240,
    likeCount: 382,
    rating: 4.8,
    status: 'PUBLISHED',
    description: '데이터 기반 사고로 사용자 경험을 설계하는 실무 중심 강좌입니다.',
    contents: [
      { id: 'c1', title: '오리엔테이션 및 커리큘럼 안내', type: 'VIDEO', durationSeconds: 480 },
      { id: 'c2', title: '데이터와 디자인 사고의 연결', type: 'VIDEO', durationSeconds: 1320 },
      { id: 'c3', title: 'UX 리서치 방법론 개요', type: 'DOCUMENT', durationSeconds: 0 },
      { id: 'c4', title: '사용자 인터뷰 실습', type: 'VIDEO', durationSeconds: 1800 },
      { id: 'c5', title: '1차 퀴즈: UX 기초 개념', type: 'QUIZ', durationSeconds: 0 },
    ],
  },
  {
    id: '2',
    title: 'AI 프로그래밍 기초: Python으로 시작하기',
    instructor: '박민준',
    instructorId: 'u4',
    category: 'AI/ML',
    level: '입문',
    thumbnail: 'https://lh3.googleusercontent.com/aida-public/AB6AXuAxrpY_2o03uAuO2wPGh-2y-BFLpTFOv2dxHqaH1SWFwkUv8rN2-I6VXRIXk5rKN1SjFNUPExCAbcMt_Lz5V7aNiS45-5IwYtxcMJpjJJvgJtPZnWpGkxsrMMT1Y6MSmUKq0qkO8rHNNMvqjSJI_cVDFn-5Z7MdGKBJI9T8OW85hgXvN4_-MJVfvyTd37SoFqGxCuXn_Qm6hPL7C1nDhNaUaEG9SRMB4IJDIgJ_T4P0KZIrjHFo9FTPR0_VqKn3X6JijA0K0tJNE',
    enrollmentCount: 3820,
    badge: 'BEST',
    likeCount: 941,
    rating: 4.9,
    status: 'PUBLISHED',
    description: 'Python 기초부터 머신러닝 모델 구현까지, AI 입문자를 위한 완성형 강좌.',
    contents: [
      { id: 'c1', title: 'Python 환경 설정', type: 'VIDEO', durationSeconds: 600 },
      { id: 'c2', title: '변수와 자료형', type: 'VIDEO', durationSeconds: 1200 },
      { id: 'c3', title: '제어문과 함수', type: 'VIDEO', durationSeconds: 1500 },
    ],
  },
  {
    id: '3',
    title: '프론트엔드 마스터: React & TypeScript',
    instructor: '이하연',
    instructorId: 'u2',
    category: '웹개발',
    level: '중급',
    thumbnail: 'https://lh3.googleusercontent.com/aida-public/AB6AXuBhJ_l4fFpx0KRkq0_nwrfZcJBgVkRqxjV8p5g7DFDQS9JYFj_1WBqYJ5YkxYLWwgB4bWSST1zqSWmELDiDlF5v7OwDBHwHDmJzYEQ5v3PYVIjJBKF-bREjJmfwFnXKMkn3_iGqjPxNNXAYFv3Wj5Z3YWEbH1Fvs6ydRrdZhRJHFQwbFgXe4fGXhDCp9dLfMeVMpHTPZ1V7Ei4-RwM6a3U7X67IM-p3VpFnY7HLFZM7wYuNUNe7X9-YPSc4kDvFbN7mnnQy_Xbf4',
    enrollmentCount: 2150,
    badge: 'BEST',
    likeCount: 528,
    rating: 4.7,
    status: 'PUBLISHED',
    description: 'React와 TypeScript로 실무 수준의 웹 앱을 만드는 중급 개발자 코스.',
    contents: [
      { id: 'c1', title: 'TypeScript 핵심 개념', type: 'VIDEO', durationSeconds: 1800 },
      { id: 'c2', title: 'React 컴포넌트 심화', type: 'VIDEO', durationSeconds: 2100 },
    ],
  },
  {
    id: '4',
    title: '클라우드 인프라 AWS 실전',
    instructor: '최서준',
    instructorId: 'u5',
    category: '클라우드',
    level: '중급',
    thumbnail: 'https://www.gstatic.com/labs-code/stitch/stitch-placeholder-300x300.svg',
    enrollmentCount: 890,
    likeCount: 213,
    rating: 4.6,
    status: 'PUBLISHED',
    description: 'AWS 핵심 서비스를 실습 중심으로 배우는 클라우드 실무 강좌.',
    contents: [],
  },
  {
    id: '5',
    title: '비즈니스 데이터 분석 with Excel & Python',
    instructor: '정수아',
    instructorId: 'u6',
    category: '데이터분석',
    level: '입문',
    thumbnail: 'https://www.gstatic.com/labs-code/stitch/stitch-placeholder-300x300.svg',
    enrollmentCount: 1560,
    likeCount: 387,
    rating: 4.5,
    status: 'PUBLISHED',
    description: 'Excel부터 Python Pandas까지 비즈니스 데이터 분석의 모든 것.',
    contents: [],
  },
  {
    id: '6',
    title: 'UX Writing: 말하는 디자인',
    instructor: '이하연',
    instructorId: 'u2',
    category: 'UI/UX',
    level: '입문',
    badge: 'NEW',
    thumbnail: 'https://www.gstatic.com/labs-code/stitch/stitch-placeholder-300x300.svg',
    enrollmentCount: 430,
    likeCount: 98,
    rating: 4.4,
    status: 'DRAFT',
    description: '사용자의 행동을 이끄는 UX 라이팅 원칙과 실습.',
    contents: [],
  },
];

export const getMyCourses = (instructorId: string) =>
  MOCK_COURSES.filter((c) => c.instructorId === instructorId);

export const getCourseById = (id: string) =>
  MOCK_COURSES.find((c) => c.id === id) ?? null;
