export const MOCK_ROADMAPS = [
  {
    id: '1',
    title: '프론트엔드 마스터: 실무 중심의 로드맵',
    description: 'HTML/CSS 기초부터 React, TypeScript까지 체계적으로 학습하는 6개월 코스.',
    category: '웹개발',
    courseCount: 8,
    enrollmentCount: 1420,
    createdBy: 'u2',
    creatorName: '이하연',
    progress: 35,
    isEnrolled: true,
    thumbnail: 'https://www.gstatic.com/labs-code/stitch/stitch-placeholder-300x300.svg',
  },
  {
    id: '2',
    title: 'AI/ML 엔지니어 입문 로드맵',
    description: 'Python 기초부터 딥러닝 모델 배포까지, AI 엔지니어 취업을 위한 완성형 로드맵.',
    category: 'AI/ML',
    courseCount: 10,
    enrollmentCount: 2380,
    createdBy: 'u4',
    creatorName: '박민준',
    progress: 0,
    isEnrolled: false,
    thumbnail: 'https://www.gstatic.com/labs-code/stitch/stitch-placeholder-300x300.svg',
  },
  {
    id: '3',
    title: 'UX 디자이너 커리어 로드맵',
    description: '리서치, 와이어프레임, 프로토타입, 포트폴리오 제작까지 UX 전 과정.',
    category: 'UI/UX',
    courseCount: 6,
    enrollmentCount: 980,
    createdBy: 'u2',
    creatorName: '이하연',
    progress: 75,
    isEnrolled: true,
    thumbnail: 'https://www.gstatic.com/labs-code/stitch/stitch-placeholder-300x300.svg',
  },
  {
    id: '4',
    title: '데이터 분석가 양성 로드맵',
    description: 'Excel, SQL, Python, 시각화 도구까지 데이터 분석 업무 전반을 커버.',
    category: '데이터분석',
    courseCount: 7,
    enrollmentCount: 1750,
    createdBy: 'u6',
    creatorName: '정수아',
    progress: 0,
    isEnrolled: false,
    thumbnail: 'https://www.gstatic.com/labs-code/stitch/stitch-placeholder-300x300.svg',
  },
  {
    id: '5',
    title: '팀을 위한 사이버 보안 에센셜',
    description: '네트워크 보안부터 침투 테스트까지, 실무 중심의 사이버 보안 입문 로드맵.',
    category: '보안',
    courseCount: 10,
    enrollmentCount: 2050,
    createdBy: 'u5',
    creatorName: '최서준',
    progress: 0,
    isEnrolled: false,
    thumbnail: 'https://lh3.googleusercontent.com/aida-public/AB6AXuBFeRNT2jIX0NwLhTV7s6rCojQVRg_-j-juFzjRI65QISW0gbA_5HEQK6un4vqgpnCea_iwvdfbrX9gF66llwIqUEL9wYD98dk2oVIsTk2p-IuCVFzzuROhE9PVoA3lLsfaSeJmN4MoWCd1DzTp0bmCth2NbG2qtVpL8iV4pr46QkEOABLiY37vxWwDBuc0S4657g-Sae5Uu5B7p4KTUiIMDTLMBvMTC60oQI1oEqKkn1rP2NIkzxUyUUY1c34b0nDjK5NAAQwZhYhh',
  },
  {
    id: '6',
    title: '클라우드 네이티브 아키텍처 (AWS/Azure)',
    description: 'AWS와 Azure를 활용한 클라우드 인프라 설계 및 DevOps 파이프라인 구축 로드맵.',
    category: '클라우드',
    courseCount: 14,
    enrollmentCount: 1580,
    createdBy: 'u5',
    creatorName: '최서준',
    progress: 0,
    isEnrolled: false,
    thumbnail: 'https://lh3.googleusercontent.com/aida-public/AB6AXuCYf5C358gYRHTx04VU97ReutHchGpgDpgag-hJtXkZudxw56iSYAjD3YJv1ykzrHDwPeIvf9v_V-fVITdppsWuOYHj4O8IAurzNppA1KlkvbCJYaRTxqdHzsnI8A3xIO8xzpSz0OISCfdEOEoqkKrkUtx1Yd54PG8PR-BISijdTrVbLcM5jRm6rQ5HX_3ADJkAMLYY-uZZF0bSsYPwxLGt9XT8q37AaZotN9_a0py8Ahdm-S9vOhcXspLctFEC754nQAS8akD-siYt',
  },
  {
    id: '7',
    title: '디지털 트랜스포메이션 리더십',
    description: '비즈니스 전략과 기술 혁신을 연결하는 DX 리더 양성 로드맵.',
    category: '비즈니스',
    courseCount: 6,
    enrollmentCount: 420,
    createdBy: 'u6',
    creatorName: '정수아',
    progress: 0,
    isEnrolled: false,
    thumbnail: 'https://lh3.googleusercontent.com/aida-public/AB6AXuBOflCVzT456kde8hx8X4R6Z1L9NQvesXUDXgflb3SN5lyDX3fXe7K8H4XKQC7noGnNXtlHHZ2DrR-698kqdqDVUJbUpYA3fZoOzCziz8sAQcR5FjOZVvlZAKE0CKIV_QENAYwfTI7xrM3VywH5IckVwtMz0hmrkM2nRYGdmYthOivV6bXGRXNtmElB54jbzcdgOhcGRVdWchxyzywzGF25J1mrhmSjaN1PefWnyIeYTfPQowPMNIVIJaMYsap2RotopPY9smBS1Ehk',
  },
];

export const getRoadmapById = (id: string) =>
  MOCK_ROADMAPS.find((r) => r.id === id) ?? null;

export const getMyRoadmaps = () =>
  MOCK_ROADMAPS.filter((r) => r.isEnrolled);
